.TH DOTF-GITIGNORE 1  "dotf-gitignore 0.0.0" 
.SH NAME
dotf\-gitignore \- Manage gitignore files
.SH SYNOPSIS
\fBdotf gitignore\fR [OPTIONS] <COMMAND>
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

.SH SUBCOMMANDS
.TP
dotf\-gitignore\-generate(1)
Generate global .gitignore file

Examples:
  dotf gitignore generate
