.TH DOTF-PACKAGE 1  "dotf-package 0.0.0" 
.SH NAME
dotf\-package \- Manage dotfiles package
.SH SYNOPSIS
\fBdotf package\fR [OPTIONS] <COMMAND>
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

.SH SUBCOMMANDS
.TP
dotf\-package\-new(1)
Create a new dotfiles package
