.TH DOTF-COMPLETION-RUST 1  "dotf-completion-rust 0.0.0" 
.SH NAME
dotf\-completion\-rust \- Generate rustup and cargo completions
.SH SYNOPSIS
\fBdotf completion rust\fR [OPTIONS]
.SH DESCRIPTION
.br
Generate rustup and cargo completions
.br

.br
Examples:
.br
  dotf completion rust
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

