.TH DOTF-COMPLETION-GO 1  "dotf-completion-go 0.0.0" 
.SH NAME
dotf\-completion\-go \- Generate golang completions
.SH SYNOPSIS
\fBdotf completion go\fR [OPTIONS]
.SH DESCRIPTION
.br
Generate golang completions
.br

.br
Examples:
.br
  dotf completion go
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

