.TH DOTF-BREWFILE 1  "dotf-brewfile 0.0.0" 
.SH NAME
dotf\-brewfile \- Manage brewfile
.SH SYNOPSIS
\fBdotf brewfile\fR [OPTIONS] <COMMAND>
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

.SH SUBCOMMANDS
.TP
dotf\-brewfile\-generate(1)
Generate Brewfile by `brew bundle dump`

Examples:
  dotf brewfile generate
