.TH DOTF-BREWFILE-GENERATE 1  "dotf-brewfile-generate 0.0.0" 
.SH NAME
dotf\-brewfile\-generate \- Generate Brewfile by `brew bundle dump`
.SH SYNOPSIS
\fBdotf brewfile generate\fR [OPTIONS]
.SH DESCRIPTION
.br
Generate Brewfile by `brew bundle dump`
.br

.br
Examples:
.br
  dotf brewfile generate
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

