.TH DOTF-LAYOUT-IMPORT 1  "dotf-layout-import 0.0.0" 
.SH NAME
dotf\-layout\-import \- Import the layout from a file
.SH SYNOPSIS
\fBdotf layout import\fR [OPTIONS]
.SH DESCRIPTION
.br
Import the layout from a file
.br

.br
Examples:
.br
  dotf layout import \-\-layout github.toml
.br
  dotf layout import \-\-source ./github.toml
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-n\fR, \fB\-\-dry\-run\fR
.br
Show what layouts will be export (not actually run)
.TP
\fB\-s\fR, \fB\-\-source\fR=\fISOURCE\fR
.br
Read layouts from the file
.TP
\fB\-\-layout\fR=\fILAYOUT\fR
.br
Read layouts from ${DF_OS_LAYOUT_DIR} directory
.TP
\fB\-h\fR, \fB\-\-help\fR
.br
Print help
