.TH DOTF-COMPLETION 1  "dotf-completion 0.0.0" 
.SH NAME
dotf\-completion \- Manage package command completions
.SH SYNOPSIS
\fBdotf completion\fR [OPTIONS] <COMMAND>
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

.SH SUBCOMMANDS
.TP
dotf\-completion\-go(1)
Generate golang completions

Examples:
  dotf completion go
.TP
dotf\-completion\-rust(1)
Generate rustup and cargo completions

Examples:
  dotf completion rust
