.TH DOTF-GITIGNORE-GENERATE 1  "dotf-gitignore-generate 0.0.0" 
.SH NAME
dotf\-gitignore\-generate \- Generate global .gitignore file
.SH SYNOPSIS
\fBdotf gitignore generate\fR [OPTIONS]
.SH DESCRIPTION
.br
Generate global .gitignore file
.br

.br
Examples:
.br
  dotf gitignore generate
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

