.TH DOTF-PACKAGE-NEW 1  "dotf-package-new 0.0.0" 
.SH NAME
dotf\-package\-new \- Create a new dotfiles package
.SH SYNOPSIS
\fBdotf package new\fR [OPTIONS] <NAME>
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-\-no\-omz\-plugin\-prefix\fR
.br
Do not use the default oh\-my\-zsh plugin prefix
.TP
\fB\-\-no\-omz\-plugins\fR
.br
Do not create oh\-my\-zsh plugins directory
.TP
\fB\-\-no\-omz\-functions\fR
.br
Do not create oh\-my\-zsh functions directory
.TP
\fB\-\-no\-omz\-completions\fR
.br
Do not create oh\-my\-zsh completions directory
.TP
\fB\-\-omz\-plugin\-name\fR=\fINAME\fR
.br
Name of the oh\-my\-zsh plugin
.TP
\fB\-h\fR, \fB\-\-help\fR
.br
Print help
.TP
<\fINAME\fR>
.br
Name of the package
