.TH DOTF-CLIPBOARD 1  "dotf-clipboard 0.0.0" 
.SH NAME
dotf\-clipboard \- Manage clipboard
.SH SYNOPSIS
\fBdotf clipboard\fR [OPTIONS] <COMMAND>
.SH OPTIONS
.TP
\fB\-D\fR, \fB\-\-debug\fR
.br
Enable debug mode
.TP
\fB\-h\fR, \fB\-\-help\fR

.SH SUBCOMMANDS
.TP
dotf\-clipboard\-parse(1)
Parse the clipboard content

Examples:
  dotf clipboard parse \-\-json
  dotf clipboard parse \-\-base64\-decode \-\-json
  dotf clipboard parse \-\-base64\-decode \-\-json \-\-copy
  dotf clipboard parse \-\-base64\-decode \-\-json \-\-sort\-key
