[project]
name = "dotf"
version = "1.4.0"
description = "Lightweight and flexible bash tool for managing dotfiles efficiently"
homepage = "https://github.com/druagoon/dotf"
repository = "https://github.com/druagoon/dotf"
license = "MIT"
