name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build-and-release:
    name: "Build and Release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install `argc` for building binaries
      - uses: sigoden/install-binary@v1
        with:
          repo: sigoden/argc
          tag: v1.22.0

      # Install `shfmt` for formatting shell scripts
      - uses: sigoden/install-binary@v1
        with:
          repo: mvdan/sh
          tag: v3.10.0
          name: shfmt

      - name: Clean up
        run: argc clean

      - name: Compile and build binaries
        run: argc build

      - name: Test binaries
        run: argc test

      - name: Distribute binaries
        run: argc dist

      - name: Release
        uses: docker://antonyurchenko/git-release:v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: |
            dist/*.tar.gz
            dist/*.sha256

      - name: Update Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v4
        with:
          token: ${{ secrets.HOMEBREW_GITHUB_API_TOKEN }}
          no_fork: true
          tap: druagoon/homebrew-brew
          formula: dotf
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
